# Site settings
title: GitHub Help
email: support@github.com
description: > # this means to ignore newlines until "baseurl:"
  Â© 2015 GitHub Inc. All rights reserved.
baseurl: "/help-doc/v007" # the subpath of your site, e.g. /blog/
#url: "http://pimgeek.github.io" # the base hostname & protocol for your site
twitter_username: github
github_username:  github

# Build settings
markdown: kramdown

gems: ['jekyll-lunr-js-search']

encoding: UTF-8

#exclude: ['v001','v002','v003','v004','v005','v006','v007']

collections:
  categories:
    output: true
    permalink: /categories/:path/
  displaying_data:
    output: true
    permalink: /articles/:title.html
  working_with_the_browser:
    output: true
    permalink: /articles/:title.html
  addons:
    output: true
    permalink: /articles/:title.html

permalink: /articles/:title.html
